modLoader="javafml"
loaderVersion="[0,)"
license="MIT"
clientSideOnly=true

[[mods]]
modId="transformableitems"
version="1.2"
displayName="Transformable Items"
logoFile="transformableitems.png"
authors="shaweel"
description="Lets you move and resize held items"

[[dependencies.transformableitems]]
	modId="forge"
	mandatory=true
	versionRange="[0,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.transformableitems]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.21.6,1.21.8]"
	ordering="NONE"
	side="BOTH"